<a href="https://colab.research.google.com/github/Raynould-Joseph/Neural-Network-and-Deep-Learning/blob/main/LAB_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a. Take an input matrix with size 5x5 and a kernel with size 3x3, perform
convolution with stride being 1 and 2.

In [ ]:
import numpy as np
x=np.array([[1,1,1,1,0],[1,1,1,0,0],[0,1,1,1,0],[0,1,0,0,1],[0,1,0,1,0]])
w=np.array([[0,0,0],[1,1,1],[1,1,0]])

In [ ]:
print("Padding -1")
print(x)
print(w)
y=np.zeros((3,3),int)
print(y)

#padding -1
#row 0
y[0,0]=np.sum(x[0:3,0:3]*w)
y[0,1]=np.sum(x[0:3,1:4]*w)
y[0,2]=np.sum(x[0:3,2:5]*w)
#row 1
y[1,0]=np.sum(x[1:4,0:3]*w)
y[1,1]=np.sum(x[1:4,1:4]*w)
y[1,2]=np.sum(x[1:4,2:5]*w)
#row 2
y[2,0]=np.sum(x[2:5,0:3]*w)
y[2,1]=np.sum(x[2:5,1:4]*w)
y[2,2]=np.sum(x[2:5,2:5]*w)
# #row 3
# y[3,0]=np.sum(x[3:6,0:3]*w)
# y[3,1]=np.sum(x[3:6,1:4]*w)
# y[3,2]=np.sum(x[3:6,2:5]*w)
# #row 4
# y[4,0]=np.sum(x[4:7,0:3]*w)
# y[4,1]=np.sum(x[4:7,1:4]*w)
# y[4,2]=np.sum(x[4:7,2:5]*w)

print(y)

print("--------------------------")
print("Padding -2")
#padding 2
print(x)
print(w)
y=np.zeros((2,2),int)
print(y)
#row 0
y[0,0]=np.sum(x[0:3,0:3]*w)
y[0,1]=np.sum(x[0:3,2:5]*w)
#row 1
y[1,0]=np.sum(x[2:5,0:3]*w)
y[1,1]=np.sum(x[2:5,2:5]*w)

print(y)


Padding -1
[[1 1 1 1 0]
 [1 1 1 0 0]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 1 0]]
[[0 0 0]
 [1 1 1]
 [1 1 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 4 3]
 [3 4 2]
 [2 2 2]]
--------------------------
Padding -2
[[1 1 1 1 0]
 [1 1 1 0 0]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 1 0]]
[[0 0 0]
 [1 1 1]
 [1 1 0]]
[[0 0]
 [0 0]]
[[4 3]
 [2 2]]


b. Apply max-pooling, average-pooling and sum-pooling to the results
from above convolutions.

In [ ]:
print("max-pooling")

print("Padding -1")
print(x)
print(w)
y=np.zeros((3,3),int)
print(y)

#padding -1
#row 0
y[0,0]=np.max(x[0:3,0:3]*w)
y[0,1]=np.max(x[0:3,1:4]*w)
y[0,2]=np.max(x[0:3,2:5]*w)
#row 1
y[1,0]=np.max(x[1:4,0:3]*w)
y[1,1]=np.max(x[1:4,1:4]*w)
y[1,2]=np.max(x[1:4,2:5]*w)
#row 2
y[2,0]=np.max(x[2:5,0:3]*w)
y[2,1]=np.max(x[2:5,1:4]*w)
y[2,2]=np.max(x[2:5,2:5]*w)
# #row 3
# y[3,0]=np.sum(x[3:6,0:3]*w)
# y[3,1]=np.sum(x[3:6,1:4]*w)
# y[3,2]=np.sum(x[3:6,2:5]*w)
# #row 4
# y[4,0]=np.sum(x[4:7,0:3]*w)
# y[4,1]=np.sum(x[4:7,1:4]*w)
# y[4,2]=np.sum(x[4:7,2:5]*w)

print(y)
max_pool_1=y

print("--------------------------")
print("Padding -2")
#padding 2
print(x)
print(w)
y=np.zeros((2,2),int)
print(y)
#row 0
y[0,0]=np.max(x[0:3,0:3]*w)
y[0,1]=np.max(x[0:3,2:5]*w)
#row 1
y[1,0]=np.max(x[2:5,0:3]*w)
y[1,1]=np.max(x[2:5,2:5]*w)

print(y)
max_pool_2=y
"""----------------------------------------------"""
print("Average-pooling")
print("Padding -1")
print(x)
print(w)
y=np.zeros((3,3),int)
print(y)

#padding -1
#row 0
y[0,0]=np.average(x[0:3,0:3]*w)
y[0,1]=np.average(x[0:3,1:4]*w)
y[0,2]=np.average(x[0:3,2:5]*w)
#row 1
y[1,0]=np.average(x[1:4,0:3]*w)
y[1,1]=np.average(x[1:4,1:4]*w)
y[1,2]=np.average(x[1:4,2:5]*w)
#row 2
y[2,0]=np.average(x[2:5,0:3]*w)
y[2,1]=np.average(x[2:5,1:4]*w)
y[2,2]=np.average(x[2:5,2:5]*w)
# #row 3
# y[3,0]=np.sum(x[3:6,0:3]*w)
# y[3,1]=np.sum(x[3:6,1:4]*w)
# y[3,2]=np.sum(x[3:6,2:5]*w)
# #row 4
# y[4,0]=np.sum(x[4:7,0:3]*w)
# y[4,1]=np.sum(x[4:7,1:4]*w)
# y[4,2]=np.sum(x[4:7,2:5]*w)

print(y)
avg_pool_1=y

print("--------------------------")
print("Padding -2")
#padding 2
print(x)
print(w)
y=np.zeros((2,2),int)
print(y)
#row 0
y[0,0]=np.average(x[0:3,0:3]*w)
y[0,1]=np.average(x[0:3,2:5]*w)
#row 1
y[1,0]=np.average(x[2:5,0:3]*w)
y[1,1]=np.average(x[2:5,2:5]*w)

print(y)
avg_pool_2=y

"""----------------------------------------------"""

print("Sum-pooling")
print("Padding -1")
print(x)
print(w)
y=np.zeros((3,3),int)
print(y)

#padding -1
#row 0
y[0,0]=np.sum(x[0:3,0:3]*w)
y[0,1]=np.sum(x[0:3,1:4]*w)
y[0,2]=np.sum(x[0:3,2:5]*w)
#row 1
y[1,0]=np.sum(x[1:4,0:3]*w)
y[1,1]=np.sum(x[1:4,1:4]*w)
y[1,2]=np.sum(x[1:4,2:5]*w)
#row 2
y[2,0]=np.sum(x[2:5,0:3]*w)
y[2,1]=np.sum(x[2:5,1:4]*w)
y[2,2]=np.sum(x[2:5,2:5]*w)
# #row 3
# y[3,0]=np.sum(x[3:6,0:3]*w)
# y[3,1]=np.sum(x[3:6,1:4]*w)
# y[3,2]=np.sum(x[3:6,2:5]*w)
# #row 4
# y[4,0]=np.sum(x[4:7,0:3]*w)
# y[4,1]=np.sum(x[4:7,1:4]*w)
# y[4,2]=np.sum(x[4:7,2:5]*w)

print(y)
sum_pool_1=y

print("--------------------------")
print("Padding -2")
#padding 2
print(x)
print(w)
y=np.zeros((2,2),int)
print(y)
#row 0
y[0,0]=np.sum(x[0:3,0:3]*w)
y[0,1]=np.sum(x[0:3,2:5]*w)
#row 1
y[1,0]=np.sum(x[2:5,0:3]*w)
y[1,1]=np.sum(x[2:5,2:5]*w)

print(y)
sum_pool_2=y







max-pooling
Padding -1
[[1 1 1 1 0]
 [1 1 1 0 0]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 1 0]]
[[0 0 0]
 [1 1 1]
 [1 1 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
--------------------------
Padding -2
[[1 1 1 1 0]
 [1 1 1 0 0]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 1 0]]
[[0 0 0]
 [1 1 1]
 [1 1 0]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
Average-pooling
Padding -1
[[1 1 1 1 0]
 [1 1 1 0 0]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 1 0]]
[[0 0 0]
 [1 1 1]
 [1 1 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
--------------------------
Padding -2
[[1 1 1 1 0]
 [1 1 1 0 0]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 1 0]]
[[0 0 0]
 [1 1 1]
 [1 1 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
Sum-pooling
Padding -1
[[1 1 1 1 0]
 [1 1 1 0 0]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 1 0]]
[[0 0 0]
 [1 1 1]
 [1 1 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[4 4 3]
 [3 4 2]
 [2 2 2]]
--------------------------
Padding -2
[[1 1 1 1 0]
 [1 1 1 0 0]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 1 0]]
[[0 0 0]
 [1 1 1]
 [1 1 0]]
[[0 0]
 [0 0]]
[[4 3]

c. Visualize the flattened version of the pooled feature maps from [Q1b]

In [ ]:
flat = [x for row in max_pool_1 for x in row]
print(flat)
flat = [x for row in max_pool_2 for x in row]
print(flat)
flat = [x for row in avg_pool_1 for x in row]
print(flat)
flat = [x for row in avg_pool_2 for x in row]
print(flat)
flat = [x for row in sum_pool_1 for x in row]
print(flat)
flat = [x for row in sum_pool_2 for x in row]
print(flat)


[8, 8, 8, 8, 8, 8, 8, 8, 8]
[1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0]
[4, 4, 3, 3, 4, 2, 2, 2, 2]
[4, 3, 2, 2]


d. With weights being randomly chosen and bias being 1, learn the
weights and bias over an epoch for the flattened arrays from [Q1c]